"""Caddy configuration renderer."""
from __future__ import annotations

from app_register.domain.models import AppServerRecord
from app_register.ports.proxy import ProxyConfigRenderer


class CaddyProxyRenderer(ProxyConfigRenderer):
    def __init__(self, *, public_listen: str, api_prefixes: list[str]) -> None:
        self._listen = public_listen
        self._prefixes = api_prefixes

    def render(self, servers: list[AppServerRecord]) -> str:
        targets = [s.upstream for s in servers]
        if not targets:
            return f"""# Generated by kairo-register — no healthy app servers
{self._listen} {{
	respond "Kairo: no app servers registered" 503
}}
"""
        upstreams = " ".join(targets)
        lines = [
            "# Generated by kairo-register — do not edit manually",
            "{",
            "\tauto_https off",
            "}",
            "",
            "(kairo_api) {",
            f"\treverse_proxy {upstreams} {{",
            "\t\ttransport http {",
            "\t\t\tversions 1.1 2",
            "\t\t}",
            "\t}",
            "}",
            "",
            f"{self._listen} {{",
            "\tencode gzip zstd",
            "",
        ]
        for prefix in self._prefixes:
            if prefix in ("/docs", "/openapi.json") or prefix.startswith("/docs"):
                pattern = prefix.rstrip("/") + "*"
                lines.append(f"\thandle {pattern} {{")
            elif prefix.endswith("*"):
                lines.append(f"\thandle {prefix} {{")
            else:
                lines.append(f"\thandle {prefix}/* {{")
            lines.append("\t\timport kairo_api")
            lines.append("\t}")
            lines.append("")
        lines.append("\thandle {")
        lines.append("\t\timport kairo_api")
        lines.append("\t}")
        lines.append("}")
        return "\n".join(lines) + "\n"
