"""Nginx configuration renderer."""
from __future__ import annotations

from app_register.domain.models import AppServerRecord
from app_register.ports.proxy import ProxyConfigRenderer


class NginxProxyRenderer(ProxyConfigRenderer):
    def __init__(self, *, public_listen: str) -> None:
        self._listen = public_listen.strip(":") or "80"

    def render(self, servers: list[AppServerRecord]) -> str:
        targets = [s.upstream for s in servers]
        if not targets:
            return f"""# Generated by kairo-register
server {{
    listen {self._listen};
    return 503 'no app servers registered';
}}
"""
        upstream_lines = "\n".join(f"    server {t};" for t in targets)
        return f"""# Generated by kairo-register
upstream kairo_app {{
{upstream_lines}
}}

server {{
    listen {self._listen};
    client_max_body_size 50m;

    location / {{
        proxy_pass http://kairo_app;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
}}
"""
