import structlog
import logging
import sys
from opentelemetry.sdk._logs import LoggingHandler
from app.core.config import settings

def setup_logging():
    log_level = getattr(logging, settings.LOG_LEVEL.upper(), logging.DEBUG)
    
    # Shared processors (extract context, timestamp, log level, etc.)
    shared_processors = [
        structlog.stdlib.filter_by_level,
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
    ]
    
    # Configure structlog to prepare the event dict for logging formatters
    structlog.configure(
        processors=shared_processors + [
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )

    # Foreign pre-chain for logs not generated by structlog (e.g., uvicorn, sqlalchemy)
    foreign_pre_chain = [
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
    ]

    # 1. Terminal Console Formatter
    level_styles = {
        "CRITICAL": "magenta",
        "EXCEPTION": "magenta",
        "ERROR": "red",
        "WARN": "yellow",
        "WARNING": "yellow",
        "INFO": "green",
        "DEBUG": "blue",
        "NOTSET": "default",
    }
    padded_level_styles = {f"{k:^8}": v for k, v in level_styles.items()}
    
    console_renderer = structlog.dev.ConsoleRenderer(
        colors=True, 
        exception_formatter=structlog.dev.plain_traceback,
        level_styles=padded_level_styles
    )

    def console_formatter_processor(logger, method_name, event_dict):
        ed = event_dict.copy()
        if "level" in ed:
            ed["level"] = f"{ed['level'].upper():^8}"
        return console_renderer(logger, method_name, ed)

    console_formatter = structlog.stdlib.ProcessorFormatter(
        processor=console_formatter_processor,
        foreign_pre_chain=foreign_pre_chain,
    )
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(console_formatter)
    
    handlers = [console_handler]

    # 2. OTel JSON Formatter
    if settings.OTEL_ENABLED:
        json_formatter = structlog.stdlib.ProcessorFormatter(
            processor=structlog.processors.JSONRenderer(),
            foreign_pre_chain=foreign_pre_chain,
        )
        otel_handler = LoggingHandler()
        otel_handler.setFormatter(json_formatter)
        handlers.append(otel_handler)

    # Clear root handlers and apply ours
    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.setLevel(log_level)
    for handler in handlers:
        root_logger.addHandler(handler)

    # Hijack Uvicorn, SQLAlchemy, and other foreign loggers
    foreign_loggers = (
        "uvicorn", 
        "uvicorn.error", 
        "uvicorn.access",
        "sqlalchemy",
        "sqlalchemy.engine",
        "sqlalchemy.engine.Engine",
        "aiosqlite"
    )
    for logger_name in foreign_loggers:
        f_logger = logging.getLogger(logger_name)
        f_logger.handlers.clear()
        f_logger.propagate = True

    # Print sample logs if in development mode
    if settings.ENV in ("development", "dev"):
        demo_logger = structlog.get_logger("system.logging")
        demo_logger.debug("Sample debug log")
        demo_logger.info("Sample info log")
        demo_logger.warning("Sample warning log")
        demo_logger.error("Sample error log")
        demo_logger.critical("Sample critical log")
