%%{init: {
  "theme": "dark",
  "flowchart": {
    "nodeSpacing": 50,
    "rankSpacing": 60
  }
}}%%

flowchart LR

	%% Actors (outside system boundary conceptually)
	User[User]

	%% System boundary containers
	subgraph Kairo[Kairo System]

		Edge["Edge Container (Nginx Reverse Proxy)"]

		subgraph Apps[Application Services]
			Web[Web Frontend - Nginx Static]
			API[API Service]
			WS[WebSocket Service]

			DB_Worker[DB Worker Service]
			Blob_Worker[Blob Worker Service]
			Thumb_Worker[Thumbnail Worker Service]
		end

		Redis[(Redis)]
		Postgres[(PostgreSQL)]
		Storage[(Object Storage - S3/MinIO)]

		OTEL[OpenTelemetry Collector]

		subgraph CP[Control Plane]
			Prometheus[(Prometheus)]
			Grafana[(Grafana)]
			Loki[(Loki)]
			Tempo[(Tempo)]
		end
	end

	User -->|HTTP| Edge
	User <-->|WebScocket| Edge

	Edge -->|HTTP| Web
	Edge -->|HTTP| API
	Edge <-->|WebScocket| WS

	API -->|SQL| Postgres
	API -->|Redis Pub/Sub| Redis
	API -->|Redis XADD Streams| Redis
	API -->|S3 API| Storage

	WS -->|Redis Pub/Sub| Redis
	WS -->|Redis XADD Streams| Redis
	WS -->|SQL| Postgres

	DB_Worker -->|SQL| Postgres
	DB_Worker -->|"XREADGROUP (db-workers-group)"| Redis


	Blob_Worker -->|"XREADGROUP (blob-workers-group)"| Redis
	Blob_Worker -->|Redis XADD Streams| Redis
	Blob_Worker -->|S3 API| Storage
    Blob_Worker -->|SQL| Postgres

	Thumb_Worker -->|"XREADGROUP (thumbnail-workers-group)"| Redis
	Thumb_Worker -->|Redis Pub/Sub| Redis
	Thumb_Worker -->|S3 API| Storage

	%% Control Plane connections (monitoring)
	OTEL -->|Prometheus Metrics| Web
	OTEL -->|Prometheus Metrics| API
	OTEL -->|Prometheus Metrics| WS
	OTEL -->|Prometheus Metrics| DB_Worker
	OTEL -->|Prometheus Metrics| Blob_Worker
	OTEL -->|Prometheus Metrics| Thumb_Worker

	Prometheus -->|Scrape Metrics| OTEL

	Web -->|stdout logs| OTEL
	API -->|stdout logs| OTEL
	WS -->|stdout logs| OTEL
	DB_Worker -->|stdout logs| OTEL
	Blob_Worker -->|stdout logs| OTEL
	Thumb_Worker -->|stdout logs| OTEL

	Web -->|OTLP Metrics/Traces| OTEL
	API -->|OTLP Metrics/Traces| OTEL
	WS -->|OTLP Metrics/Traces| OTEL
	DB_Worker -->|OTLP Metrics/Traces| OTEL
	Blob_Worker -->|OTLP Metrics/Traces| OTEL
	Thumb_Worker -->|OTLP Metrics/Traces| OTEL

	OTEL -->Tempo

	OTEL -->|Loki Logs| Loki

	Grafana -->|Query Metrics| Prometheus
	Grafana -->|Query Logs| Loki
	Grafana -->|Query Traces| Tempo
