%%{init: {
"theme": "dark",
"flowchart": {
    "nodeSpacing": 50,
    "rankSpacing": 60
}
}}%%

flowchart TB

	Edge["Edge Container (Nginx Reverse Proxy)"]

    subgraph API[API Service - FastAPI Container]

        App[Main FastAPI App]

        subgraph Business[Business Components]
            Auth[Auth Component]
            Room[Room Component]
            Message[Message Component]
            Attachment[Attachment Component]
            Presence[Presence Component]
        end

        Health[Health Component]

        subgraph Infra [Infrastructure Adapters]
            DBC[Database Client]
            RedisC[Redis Client]
            StorageC[Storage Client]
        end

        Obs[Observability Component]

        DevMetrics[Development Metrics App]
    end

    OTel[OTel Collector]

    Redis[(Redis)]
    Postgres[(PostgreSQL)]
    Storage[(Object Storage - S3/MinIO)]

    Edge -->|HTTP| App

    App --> Auth
    App --> Room
    App --> Message
    App --> Attachment
    App --> Presence
    App --> Health

    Auth --> RedisC

    Room --> DBC
    
    Message --> DBC
    
    Attachment --> StorageC
    Attachment --> DBC
    Attachment --> RedisC

    Presence --> RedisC

    Health --> DBC
    Health --> RedisC
    Health --> StorageC

    App --> Obs
    Auth --> Obs
    Room --> Obs
    Message --> Obs
    Attachment --> Obs
    Presence --> Obs

    App --> DevMetrics
    Auth --> DevMetrics
    Room --> DevMetrics
    Message --> DevMetrics
    Attachment --> DevMetrics
    Presence --> DevMetrics

    Obs --> OTel
    DBC --> Postgres
    RedisC --> Redis
    StorageC --> Storage
