%%{init: {
  "theme": "dark",
  "flowchart": {
    "nodeSpacing": 50,
    "rankSpacing": 60
  }
}}%%

flowchart TD

    subgraph API[API Service]

        %% Base
        Router["API Router (FastAPI)"]

        subgraph AuthModule[Authentication Module]
            direction TB
            AuthRoute[Auth Route]
            AuthMediator["Auth Mediator"]
            AuthRepo["Auth Repository"]
        end

        subgraph RoomModule[Room Management Module]
            direction TB
            RoomRoute[Room Route]
            RoomMediator["Room Mediator"]
            RoomRepo["Room Repository"]
        end

        subgraph MessageModule[Messaging Module]
            direction TB
            MessageRoute[Message Route]
            MessageMediator["Message Mediator"]
            MessageRepo["Message Repository"]
        end

        subgraph AttachmentModule[Attachment Module]
            direction TB
            AttachmentRoute[Attachment Route]
            AttachmentMediator["Attachment Mediator"]
            AttachmentRepo["Attachment Repository"]
        end

        subgraph PresenceModule[Presence Module]
            direction TB
            PresenceRoute[Presence Route]
            PresenceMediator["Presence Mediator"]
            PresenceRepo["Presence Repository"]
        end
        
        UserRepo["User Repository"]

        %% DB
        DBEngine["Database Engine (SQLAlchemy)"]

        %% Core
        Security["Security (JWT, OAuth)"]

        RedisClient["Redis Client (redis-py)"]
        StorageClient["Storage Client (boto3)"]

        %% platform
        Logging[Logging System]
        Metrics[Prometheus Metrics Client]
        Tracing[Tracing Instrumentation]

        Health[Health Check Endpoint]

    end

    subgraph CP[Control Plane]
        Prometheus[(Prometheus)]
        Loki[(Loki)]
        Tempo[(Tempo)]
    end

    Postgres[(PostgreSQL)]
    Redis[(Redis)]
    Storage[(Object Storage - S3/MinIO)]

    

    Router --> AuthRoute
    Router --> RoomRoute
    Router --> MessageRoute
    Router --> AttachmentRoute
    Router --> PresenceRoute

    AuthRoute --> AuthMediator
    RoomRoute --> RoomMediator
    MessageRoute --> MessageMediator
    AttachmentRoute --> AttachmentMediator
    PresenceRoute --> PresenceMediator

    AuthMediator --> Security

    AuthMediator --> AuthRepo
    RoomMediator --> RoomRepo
    MessageMediator --> MessageRepo
    AttachmentMediator --> AttachmentRepo
    PresenceMediator --> PresenceRepo

    AttachmentMediator --> StorageClient
    AttachmentMediator --> RedisClient

    AuthRepo --> DBEngine
    RoomRepo --> DBEngine
    MessageRepo --> DBEngine
    AttachmentRepo --> DBEngine
    PresenceRepo --> DBEngine

    DBEngine --> Postgres

    RedisClient --> Redis

    StorageClient --> Storage

    Router --> Health

    Logging --> Loki
    Metrics --> Prometheus
    Tracing --> Tempo