%%{init: {
"theme": "dark",
"flowchart": {
    "nodeSpacing": 50,
    "rankSpacing": 60
}
}}%%

flowchart TB
    APIRouter[API Router]

    subgraph Auth[Auth Component]
        Router[Auth Router]
        Service[Auth Service]
        Repository[Auth Repository]
    end

    subgraph Security[Security]
        JWT[JWT Manager]
        Password[Password Hasher]
    end

    subgraph Infra [Infrastructure Adapters]
        DBC[Database Client]
        RedisC[Redis Client]
    end

APIRouter --> Router

Router --> Service
Service --> Repository
Service --> JWT
Service --> Password

Repository --> DBC
Repository --> RedisC